baseURL: 'https://necloud.us/'
languageCode: 'en-us'
title: 'necloud'
theme: 'gohugo-theme-ananke'

params:
  hero:
    background_image: ""
  article:
    readingTime: true
    linkToMarkup: false
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: photos
      name: Photos
      url: /photos/
      weight: 2
    - identifier: notes
      name: Notes
      url: /notes/
      weight: 3
    - identifier: pages
      name: Pages
      url: /pages/
      weight: 4
    - identifier: about
      name: About
      url: /about/
      weight: 5